'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header/Header";
import Footer from "@/app/components/Footer/Footer";
import { usePathname } from "next/navigation";
import { ThemeProvider } from "@mui/material";
import { theme } from "./Theme/theme";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "PROJECT name",
//   description: "Generated by bit-by-bit",
// };

const pagesWithHeader = [
  "/"
];

const pagesWithFooter = [
  "/"
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          {pagesWithHeader.includes(pathname) && <Header/>}
          {children}
          {pagesWithFooter.includes(pathname) && <Footer/>}
        </ThemeProvider>
      </body>
    </html>
  );
}
